# all_texture_data = {
#     "copper_sword": {"item_type": "sword", "size": (16, 16), "position": (1*16, 35*16)},
#     "copper_pickaxe": {"item_type": "pickaxe", "size": (16, 16), "position": (0, 35*16)},
#     "copper_axe": {"item_type": "axe", "size": (16, 16), "position": (4*16, 35*16)},
#     "grass": {"item_type": "block", "size": (16, 16), "position": (0, 6*16)},
#     "dirt": {"item_type": "block", "size": (16, 16), "position": (16, 6*16)},
#     "stone": {"item_type": "block", "size": (16, 16), "position": (0, 5*16)},
#     "coal_ore": {"item_type": "block", "size": (16, 16), "position": (3*16, 5*16)},
#     "tree_log": {"item_type": "tree", "size": (16, 16), "position": (13*16, 12*16)},
#     "wood_plank": {"item_type": "block", "size": (16, 16), "position": (0, 13*16)},
#     "tree_leaf": {"item_type": "tree", "size": (16, 16), "position": (0, 16*16)},
#     "leaf_block": {"item_type": "block", "size": (16, 16), "position": (0, 16*16)},
#     "apple": {"item_type": "food", "size": (16, 16), "position": (11*16, 35*16)},
#     "slime": {"item_type": "utility", "size": (16, 16), "position": (4*16, 40*16)}
# }


all_texture_data = {
    "copper_sword": {"item_type": "sword", "size": (16, 16), "position": (16, 6 * 16), "inventory_item": "default"},
    "copper_pickaxe": {"item_type": "pickaxe", "size": (16, 16), "position": (0, 6 * 16), "inventory_item": "default"},
    "copper_axe": {"item_type": "axe", "size": (16, 16), "position": (3 * 16, 6 * 16), "inventory_item": "default"},
    "grass": {"item_type": "block", "size": (16, 16), "position": (0, 0), "inventory_item": "default"},
    "dirt": {"item_type": "block", "size": (16, 16), "position": (16, 0), "inventory_item": "default"},
    "stone": {"item_type": "block", "size": (16, 16), "position": (0, 16), "inventory_item": "default"},
    "deepslate": {"item_type": "block", "size": (16, 16), "position": (16, 16), "inventory_item": "default"},
    "coal_ore": {"item_type": "block", "size": (16, 16), "position": (0, 2 * 16), "inventory_item": "coal"},
    "iron_ore": {"item_type": "block", "size": (16, 16), "position": (16, 2 * 16), "inventory_item": "iron"},
    "gold_ore": {"item_type": "block", "size": (16, 16), "position": (2 * 16, 2 * 16), "inventory_item": "gold"},
    "redstone_ore": {"item_type": "block", "size": (16, 16), "position": (3 * 16, 2 * 16), "inventory_item": "redstone"},
    "emerald_ore": {"item_type": "block", "size": (16, 16), "position": (4 * 16, 2 * 16), "inventory_item": "emerald"},
    "lapis_lazuli_ore": {"item_type": "block", "size": (16, 16), "position": (5 * 16, 2 * 16), "inventory_item": "lapis_lazuli"},
    "diamond_ore": {"item_type": "block", "size": (16, 16), "position": (6 * 16, 2 * 16), "inventory_item": "diamond"},
    "deepslate_coal_ore": {"item_type": "block", "size": (16, 16), "position": (0, 3 * 16), "inventory_item": "coal"},
    "deepslate_iron_ore": {"item_type": "block", "size": (16, 16), "position": (16, 3 * 16), "inventory_item": "iron"},
    "deepslate_gold_ore": {"item_type": "block", "size": (16, 16), "position": (2 * 16, 3 * 16), "inventory_item": "gold"},
    "deepslate_redstone_ore": {"item_type": "block", "size": (16, 16), "position": (3 * 16, 3 * 16), "inventory_item": "redstone"},
    "deepslate_emerald_ore": {"item_type": "block", "size": (16, 16), "position": (4 * 16, 3 * 16), "inventory_item": "emerald"},
    "deepslate_lapis_lazuli_ore": {"item_type": "block", "size": (16, 16), "position": (5 * 16, 3 * 16), "inventory_item": "lapis_lazuli"},
    "deepslate_diamond_ore": {"item_type": "block", "size": (16, 16), "position": (6 * 16, 3 * 16), "inventory_item": "diamond"},
    "coal": {"item_type": "block", "size": (16, 16), "position": (0, 12 * 16), "inventory_item": "default"},
    "iron": {"item_type": "block", "size": (16, 16), "position": (16, 12 * 16), "inventory_item": "default"},
    "gold": {"item_type": "block", "size": (16, 16), "position": (2 * 16, 12 * 16), "inventory_item": "default"},
    "redstone": {"item_type": "block", "size": (16, 16), "position": (3 * 16, 12 * 16), "inventory_item": "default"},
    "emerald": {"item_type": "block", "size": (16, 16), "position": (4 * 16, 12 * 16), "inventory_item": "default"},
    "lapis_lazuli": {"item_type": "block", "size": (16, 16), "position": (5 * 16, 12 * 16), "inventory_item": "default"},
    "diamond": {"item_type": "block", "size": (16, 16), "position": (6 * 16, 12 * 16), "inventory_item": "default"},
    "tree_log": {"item_type": "tree", "size": (16, 16), "position": (0, 4 * 16), "inventory_item": "wood_plank"},
    "tree_leaf": {"item_type": "tree", "size": (16, 16), "position": (16, 4 * 16), "inventory_item": "packed_leaf"},
    "wood_plank": {"item_type": "block", "size": (16, 16), "position": (0, 5 * 16), "inventory_item": "default"},
    "packed_leaf": {"item_type": "block", "size": (16, 16), "position": (16, 5 * 16), "inventory_item": "default"},
    "torch": {"item_type": "block", "size": (16, 16), "position": (5 * 16, 11 * 16), "inventory_item": "default"},
    "slime": {"item_type": "utility", "size": (16, 16), "position": (4 * 16, 11 * 16), "inventory_item": "default"},
    "apple": {"item_type": "food", "size": (16, 16), "position": (11 * 16, 6 * 16), "inventory_item": "default"},
}
