WINDOW_WIDTH = 800
WINDOW_HEIGHT = 800
FRAMES_PER_SECOND = 60

BLOCK_SIZE = 8
BLOCKS_IN_ATLAS_X = 2
BLOCKS_IN_ATLAS_Y = 2

CHUNK_WIDTH = BLOCK_SIZE * 32
CHUNK_HEIGHT = BLOCK_SIZE * 32

WORLD_WIDTH = 10000


HORIZONTAL_SPEED = 10
JUMP_HEIGHT = 16
TERMINAL_VELOCITY = 3

