WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FRAMES_PER_SECOND = 60

HORIZONTAL_SCROLL_DELAY_FACTOR = 4
VERTICAL_SCROLL_DELAY_FACTOR = 4

BLOCKS_IN_ATLAS_X = 2
BLOCKS_IN_ATLAS_Y = 2

BLOCK_SIZE = 32

# num of blocks per chunk
CHUNK_WIDTH = 10
CHUNK_HEIGHT = 10

# num of blocks in world
WORLD_WIDTH = 100000
WORLD_HEIGHT = 100


HORIZONTAL_SPEED = 10
GRAVITY = 2
JUMP_HEIGHT = 24
TERMINAL_VELOCITY = 5

