PLAYER_SAVE_FOLDER = "player_save_files"
WORLD_SAVE_FOLDER = "world_save_files"


WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FRAMES_PER_SECOND = 144

HORIZONTAL_SCROLL_DELAY_FACTOR = 10
VERTICAL_SCROLL_DELAY_FACTOR = 10


BLOCK_SIZE = 32

# Number of blocks per chunk
CHUNK_WIDTH = 32
CHUNK_HEIGHT = 32

# Number of blocks in the world
WORLD_WIDTH = 100000
WORLD_HEIGHT = 1000

# Player related
PLAYER_HORIZONTAL_SPEED = 1500
GRAVITY = 3000
PLAYER_JUMP_HEIGHT = 700

REACH = 5  # 5 blocks

# Inventory
COLUMN_SLOTS = 9
ROW_SLOTS = 3


# SlimeEnemy related
ENEMY_HORIZONTAL_SPEED = 500
ENEMY_JUMP_HEIGHT = 900
